### ISSUE TITLE
Offset of Multiple Lines with Variable offset Values 

### ISSUE THREAD

**Issue by khatriharsh** [seghier/Clipper2GH#2]
Can it done with this Clipper
Offset of Multiple Lines with Variable offset Values[for each of those Lines/Curves] having Proper Angled Edges at the End

**Comment by seghier** [comment]
If you mean multiple offset with combined output , this not possible.

![image](https://github.com/seghier/Clipper2GH/assets/6026588/f1dd4151-b834-4b5d-b228-5d1dbd2736bb)

**Comment by khatriharsh** [comment]
No there are N number of lines with N number of offsets.. they're end product to be combined.

**Comment by seghier** [comment]
I don't understand your question.
Can you show an example?

**Comment by khatriharsh** [comment]
![image](https://github.com/seghier/Clipper2GH/assets/50658843/0ca8fef7-561c-422d-be0e-9a8f9f724041)

**Comment by khatriharsh** [comment]
Can this be done??

**Comment by seghier** [comment]
Did you try to create this?
Based on your image you can get this result by using Graft  because the curves in the same list will combined.

![image](https://github.com/seghier/Clipper2GH/assets/6026588/673207f0-7f30-46da-8557-fab01b1de2d5)

**Comment by khatriharsh** [comment]
yes I made filter for line close by that's not relevant.. how can I get offsets to these lines.??

**Comment by khatriharsh** [comment]
yes.. graft is not solution I want those outer edges to be fillet

**Comment by seghier** [comment]
Clipper always combined curves in the same list , the only solution is graft.

**Comment by seghier** [comment]
This is not related to Clipper , you may ask in the forum
