### ISSUE TITLE
issue on offset

### ISSUE THREAD

**Issue by Sonderwoods** [seghier/Clipper2GH#3]
The offset is not making the corners correct where a closed curve starts/ends.
See below in Clipper2
![image](https://github.com/seghier/Clipper2GH/assets/19936679/dd3ed978-3b94-475a-89cb-2398ee70defe)

Same geometry in Clipper1
![image](https://github.com/seghier/Clipper2GH/assets/19936679/bbeb7894-9089-4b87-b5eb-3b5ddb2f7d78)

**Comment by seghier** [comment]
MiterLimit = 2 by default , you need to increase it and use 

**JoinType**: Mitter

**EndType**: Joined or Polygon

![image](https://github.com/seghier/Clipper2GH/assets/6026588/7366ac77-219f-4280-85f5-05d4a7b2864a)

**Comment by Sonderwoods** [comment]
hey, thanks! I realized that i also needed to change the endtype.

Fast reply, I love it!
